### ISSUE TITLE
Invalid Request (404)

### ISSUE THREAD

**Issue by TitouBilou** [tataille/MMM-FreeBox-Monitor#3]
After solving the black screen issue with the new fix for MMM-FreeBox-Monitor (2016-11-22), when the module appear on the Magic Mirror screen it shows now: "Requête Invalide (404)". I do not see the autorisation question on the LCD display from the Freebox server (it just displays the hour)? Any idea?
Regards,

**Comment by TitouBilou** [comment]
Here are the logs and a screen capture:

--> null
CallbackCheckAuthorize -> {"msg":"Requête invalide (404)","success":false,"error_code":"invalid_request"}

![image](https://cloud.githubusercontent.com/assets/23405709/20542957/38e22a7c-b104-11e6-9e65-779772ff2224.png)

**Comment by tataille** [comment]
Could you try with official internal ip 192.168.0.254

**Comment by TitouBilou** [comment]
Actually that would be quite a hassle as I have OpenVPN and Email servers (RPis), all my equipment is on static IP... To make it short, this means quite a lot of work to reconfigure all the connections...
For information I've tried to change the 'internal ip' by the 'external ip: port' in the Magic Mirror config.js file and it didn't change anything, still the 'Invalid Request'. Can this exclude the fact that the problem is linked to the internal ip address?
Regards,

**Comment by tataille** [comment]
Could you try to type in a browser

http://mafreebox.freebox.fr/api_version

And replace mafreebox.freebox.fr with your IP

**Comment by TitouBilou** [comment]
My Freebox server api_version is 3.0 as seen below:
"api_version":"3.0","api_base_url":"\/api\/","device_type":"FreeboxServer1,1"
Regards,

**Comment by tataille** [comment]
Did you try with the two ips

**Comment by TitouBilou** [comment]
I actually tried four ips:
- http://mafreebox.freebox.fr/api_version
- http://internal ip/api_version
- http://external ip:port1/api_version
- https://external ip:port2/api_version
The result is always the same: api version 3.0
Regards,

**Comment by tataille** [comment]
could you try to configure the http://mafreebox.freebox.fr in the config of
MagicMirror for FreeboxModule?

2016-11-23 21:01 GMT+01:00 TitouBilou notifications@github.com:

**Comment by TitouBilou** [comment]
Still "invalid request (404)".

**Comment by TitouBilou** [comment]
Here is the error message:
![capture](https://cloud.githubusercontent.com/assets/23405709/20578029/7dc45ff4-b1c5-11e6-864a-b80e230828d1.PNG)

**Comment by tataille** [comment]
Ok, simple, open your freebox admin page... Freebox Management -> Access
management

![Uploading 2016-11-23_21-43-40.png…]()


​

2016-11-23 21:40 GMT+01:00 TitouBilou <notifications@github.com>:

**Comment by TitouBilou** [comment]
It's working like a charm!!! Great!!!
Thanks very much for the module and the big help to solve this issue.
Greatly appreciated!
Regards,

**Comment by tataille** [comment]
Avec Plaisir

2016-11-23 22:05 GMT+01:00 TitouBilou notifications@github.com:
