### ISSUE TITLE
Log

### ISSUE THREAD

**Issue by energy01** [tataille/MMM-FreeBox-Monitor#5]
Bonjour,

merci pour le module il est pas mal
un petit problème que j'ai eu c'est que cela génère énormément de message en sortie "log"
après 1 journée lancé via "pm2" j'avais un fichier mm-out-0.log de plus de 9 Go qui donc a saturé la carte SD de mon Pi d'ou plantage ...

perso j'ai mis en commentaire tous les console.log (sauf pour les "error") ça semble un peu mieux ...

@+
Anthony.

**Comment by tataille** [comment]
OK merci je vais corriger

**Comment by tataille** [comment]
Corrigé, il faut récupérer les fichiers et remplacer le code du plugin
