### ISSUE TITLE
probleme fichier freebox.txt

### ISSUE THREAD

**Issue by ocverclock** [tataille/MMM-FreeBox-Monitor#8]
bonjour,
le fichier freebox.txt n'est pas crée a l'autorisation.
ce qui fait que a chaque démarrage du mirroir, il me demande de l'autoriser sur la freebox.
comment faire ?

**Comment by tataille** [comment]
Votre répertoire est il en écriture? Quel user lance le miroir?

**Comment by ocverclock** [comment]
drwxr-xr-x  5 pi pi  4096 mai   12 16:07 MMM-FreeBox-Monitor
pour le user que lance le mirroir je ne sais pas

**Comment by tataille** [comment]
Essayez de faire un
chmod 777
Dans le répertoire.

**Comment by jmtaillant** [comment]
Pour connaître le user, mirror lancé, connectez vous en ssh et lancer la commande:

> ps -e -o pid,user,comm

**Comment by ocverclock** [comment]
après une mise a jour et upgrade, tout est rentrée dans l'ordre. le fichier freebox.txt est bien crée, je ne pensais pas le retrouver dans le dossier MagicMirror, je pensais qu'il serait dans le dossier du module. bref, ca fonctionne c'est la principal. Merci beaucoup de ta réactivité.
